import { ThemeProvider } from "@components-home/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { Oswald } from "next/font/google";

const inter = Oswald({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata = {
  title: "FAB-INACAP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="es">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          storageKey="Theme"
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
