import { ThemeProvider } from "@components-home/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import Header from "@components-home/Header";
import Footer from "@components-home/Footer";
import "../globals.css";
import { Oswald } from "next/font/google";

const inter = Oswald({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata = {
  title: "FAB-INACAP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="es">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          storageKey="Theme"
        >
          <Header />
          {children}
          <Toaster />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
